### ISSUE TITLE
js_binary does not work on Windows

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#101]
I'm trying to get rules_swc working on Windows, and have reached the point where it fails inside `js_binary`:

```
    INFO: Invocation ID: d3e53c76-a957-42a2-b151-46337966704c
ERROR: C:/users/mhill/_bazel_mhill/bqmuzrid/external/aspect_rules_swc/swc/BUILD.bazel:56:10: in js_binary rule @aspect_rules_swc//swc:cli:
Traceback (most recent call last):
        File "C:/users/mhill/_bazel_mhill/bqmuzrid/external/aspect_rules_js/js/private/js_binary.bzl", line 210, column 32, in _js_binary_impl
                launcher = _create_launcher(ctx)
        File "C:/users/mhill/_bazel_mhill/bqmuzrid/external/aspect_rules_js/js/private/js_binary.bzl", line 193, column 70, in _create_launcher
                launcher = create_windows_native_launcher_script(ctx, ctx.outputs.launcher_sh) if ctx.attr.is_windows else bash_launcher
Error: No attribute 'launcher_sh' in outputs. Make sure you declared a rule output with this name.
ERROR: C:/users/mhill/_bazel_mhill/bqmuzrid/external/aspect_rules_swc/swc/BUILD.bazel:56:10: Analysis of target '@aspect_rules_swc//swc:cli' failed
```

Sure enough, there is no `launcher_sh` attribute:

https://github.com/aspect-build/rules_js/blob/main/js/private/js_binary.bzl

**Comment by gregmagolan** [comment]
I should be able to pick this up next week

**Comment by kormide** [comment]
@matthewjh The part of the code your trace references has changed significantly and I can't see how it would occur now. I'm going to close this for now but please re-open if you encounter the issue on the latest release.
