### ISSUE TITLE
[Bug]: rules_js fails to parse pnpm lockfile v6 for packages with long lists of peer dependencies

### ISSUE THREAD

**Issue by twheys** [aspect-build/rules_js#1015]
### What happened?

Apparently pnpm lockfile v6 uses complex yml mapping keys for packages with long lists of peer dependencies which is not parsed correctly by rules_js. I get the below exception

```
Repository rule npm_translate_lock defined at:
  /private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/npm_translate_lock.bzl:101:37: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 78, column 58, in _impl
		importers, packages = translate_to_transitive_closure(
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 127, column 53, in translate_to_transitive_closure
		package, package_info = _gather_package_info(package_path, package_snapshot)
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 82, column 17, in _gather_package_info
		fail(msg)
Error in fail: expected package resolution to have a name field
ERROR: /Users/theys/r9/R9/WORKSPACE:257:19: fetching npm_translate_lock rule //external:npm: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 78, column 58, in _impl
		importers, packages = translate_to_transitive_closure(
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 127, column 53, in translate_to_transitive_closure
		package, package_info = _gather_package_info(package_path, package_snapshot)
	File "/private/var/tmp/_bazel_theys/c47bd7bac752f67cacbe3862d74d80c0/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 82, column 17, in _gather_package_info
		fail(msg)
```

This exception is thrown while interpreting the following entry in the pnpm v6 lockfile (note: I redacted the module names because these are internally published packages and I'd prefer not to share them). It appears that pnpm's yaml serializer uses complex mapping keys (https://yaml.org/spec/1.2.2/#example-mapping-between-sequences) for very long key names and the rules_js yaml parser does not interpret this correctly.

```
  ? /@myorg/foobar@1(@babel/runtime@7.20.6)(@myorg/pkg1@1)(@myorg/pkg2@1)(@myorg/pkg3@1)(@myorg/pkg4@1)(@myorg/pkg4@1)(@myorg/pkg5@1)(@myorg/pkg5@1)(@myorg/pkg6@1)(@myorg/pkg7@1)(@myorg/pkg8@1)(@myorg/pkg9@1)(@myorg/pkg10@1)(@myorg/pkg11@1)(@myorg/pkg12@1)(@myorg/pkg13@1)(@myorg/pkg14@1)(@myorg/pkg15@1)(@myorg/pkg16@1)(@myorg/pkg17@1)(@myorg/pkg18@1)(@myorg/pkg19@1)(@myorg/pkg20@1)(@myorg/pkg21@1)(@myorg/pkg22@1)(@myorg/pkg23@1)(@myorg/pkg24@1)(@myorg/pkg25@1)(@myorg/pkg26@1)(@myorg/pkg27@1)(@myorg/pkg28@1)(@myorg/pkg29@1)(@myorg/pkg30@1)(classnames@2.3.1)(react-dom@17.0.2)(react@17.0.2)
  : resolution: {integrity: ...}
    peerDependencies:
      '@babel/runtime': ^7.17.2
```

### Version

This issue appears in rules_js@v1.24.0 and all versions thereafter

### How to reproduce

```shell
In any lockfile, manually change an entry to use a complex yaml mapping key, then build any bazel target.
```

**Comment by jbedard** [comment]
@twheys do you have a real lockfile that we can test with? Or maybe you can try the fix from https://github.com/aspect-build/rules_js/pull/1016?

**Comment by twheys** [comment]
Hi @jbedard, thanks for addressing this so quickly. The example i provided is a real one where i just modified the package names. I patched my aspect_rules_js with the two commits from your PR and I can confirm that I am able to install and build now. From my perspective, it is good to merge

**Comment by jbedard** [comment]
Thanks for verifying that 👍
