### ISSUE TITLE
[Bug]: Node FS patches regression for file URLs

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#1105]
### What happened?

According to the Node.js [fs docs](https://nodejs.org/api/fs.html#fspromisesrealpathpath-options), many functions accept file URL strings or URL objects in addition to regular path strings.

The "file URL string" case, for instance, used to work but was - I believe - broken by https://github.com/aspect-build/rules_js/pull/1007:

```typescript
import { realpathSync } from "fs";

realpathSync("file:///Users/mhill/file");
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of URL
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.isAbsolute (node:path:1157:5)
    at fs_isEscape (/Users/mhill/bazel/3c3e59429c86c7585f0ffa57350a75ac/external/aspect_rules_js/js/private/node-patches/fs.js:738:19)
    at Object.realpathSync (/Users/mhill/bazel/3c3e59429c86c7585f0ffa57350a75ac/external/aspect_rules_js/js/private/node-patches/fs.js:195:29)
    at finalizeResolution (node:internal/modules/esm/resolve:336:21)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1116:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

    http_archive(
        name = "aspect_rules_js",
        sha256 = "3e237129b3554373a80c681c4b47348f91c294ff32d4bc8f8297f40511a4eb6c",
        strip_prefix = "rules_js-1.25.4",
        url = "https://github.com/aspect-build/rules_js/releases/download/v1.25.4/rules_js-v1.25.4.tar.gz",
)

Language(s) and/or frameworks involved:

### How to reproduce

```shell
import { realpathSync } from "fs";

realpathSync("file:///Users/mhill/file");
```

**Comment by jbedard** [comment]
@matthewjh are you sure those methods accept URL strings and not only URL objects?

I seem to be getting errors when I do `realpathSync("file:///Users/Jason/.vimrc")` (directly in the node console, no bazel/rules_js involved). But that same string as a `URL` works fine (again outside rules_js): `realpathSync(new URL("file:///Users/Jason/.vimrc"))`.

However URL objects are broken with rules_js, see https://github.com/aspect-build/rules_js/pull/1106 for a potential fix that can hopefully merge soon.
