### ISSUE TITLE
[Bug]: checksum failure and Bazel crash with remote downloader

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#1150]
### What happened?

It seems that Bazel crashes when a remote RBE server tries to fetch from an npm registry.

```
(18:37:06) ERROR: An error occurred during the fetch of repository 'cypress_linux':
   Traceback (most recent call last):
	File "/bzl/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /bzl/out/external/cypress_linux/temp3739814056933006744/cypress.zip to /bzl/out/external/cypress_linux/temp3739814056933006744: null
(18:37:06) ERROR: /builds/_P_jvKxe/8/features/denali/WORKSPACE.bazel:141:21: fetching http_archive rule //external:cypress_linux: Traceback (most recent call last):
	File "/bzl/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /bzl/out/external/cypress_linux/temp3739814056933006744/cypress.zip to /bzl/out/external/cypress_linux/temp3739814056933006744: null
(18:37:06) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@rules_js_npm__prettier__2.2.0' (requested by nodes 'PACKAGE_LOOKUP:@rules_js_npm__prettier__2.2.0//')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:642)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: StringIndexOutOfBoundsException thrown during Starlark evaluation (LOADING)
	at <starlark>.download(<builtin>:0)
	at <starlark>._download_and_extract_archive(/bzl/out/external/aspect_rules_js/npm/private/npm_import.bzl:451)
	at <starlark>._npm_import_rule_impl(/bzl/out/external/aspect_rules_js/npm/private/npm_import.bzl:493)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at com.google.devtools.build.lib.remote.disk.DiskCacheClient.toPath(DiskCacheClient.java:222)
	at com.google.devtools.build.lib.remote.disk.DiskCacheClient.contains(DiskCacheClient.java:68)
	at com.google.devtools.build.lib.remote.disk.DiskAndRemoteCacheClient.downloadBlob(DiskAndRemoteCacheClient.java:158)
	at com.google.devtools.build.lib.remote.downloader.GrpcRemoteDownloader.lambda$download$2(GrpcRemoteDownloader.java:142)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
	at com.google.devtools.build.lib.remote.downloader.GrpcRemoteDownloader.download(GrpcRemoteDownloader.java:138)
	at com.google.devtools.build.lib.bazel.repository.downloader.DelegatingDownloader.download(DelegatingDownloader.java:62)
	at com.google.devtools.build.lib.bazel.repository.downloader.DownloadManager.download(DownloadManager.java:258)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkBaseExternalContext.download(StarlarkBaseExternalContext.java:484)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
	at net.starlark.java.eval.Eval.eval(Eval.java:497)
	at net.starlark.java.eval.Eval.exec(Eval.java:271)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:682)
	at net.starlark.java.eval.Eval.eval(Eval.java:497)
	at net.starlark.java.eval.Eval.exec(Eval.java:271)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execIf(Eval.java:207)
	at net.starlark.java.eval.Eval.exec(Eval.java:283)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:173)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:638)
	at net.starlark.java.eval.Starlark.call(Starlark.java:604)
	at com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryFunction.fetch(StarlarkRepositoryFunction.java:220)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:411)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:342)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:571)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
	Suppressed: com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException: Checksum was cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e but wanted c987aba64bec78ce22283fc15cb61491057968ab78b503ea6865ba12c663cf2bb4afbb1565934f256e18f0cc8a9a2729eade365d43dc05503e1fab01de0aa777
		at com.google.devtools.build.lib.bazel.repository.downloader.HashOutputStream.check(HashOutputStream.java:86)
		at com.google.devtools.build.lib.bazel.repository.downloader.HashOutputStream.close(HashOutputStream.java:77)
		at com.google.devtools.build.lib.remote.downloader.GrpcRemoteDownloader.lambda$download$2(GrpcRemoteDownloader.java:140)
		... 43 more
error Command failed with exit code 37.
```

### Version

Reproduced with bazel 5.2, 6.2, rules_js 1.29.2 (and some earlier)

### Any other information?

The rules_nodejs `yarn_install` works using `_auth`.
The rules_js `_auth` is being passed to the failing `rctx.download` call.

**Comment by alexeagle** [comment]
Seems like a Bazel bug. rules_js auth works in a local setting, so whatever Remote downloader API is probably not doing it the same way.
