### ISSUE TITLE
npm package remark failed to fetch

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#148]
repro: https://github.com/aspect-build/bazel-examples/pull/new/next

```
% bazel test ...
INFO: Repository npm__stringify-entities__4.0.2 instantiated at:
  /home/alexeagle/Projects/bazel-examples/next.js/WORKSPACE.bazel:30:17: in <toplevel>
  /home/alexeagle/.cache/bazel/_bazel_alexeagle/1112fa9a04c6878cb3f2bf123baf106a/external/npm/repositories.bzl:3979:15: in npm_repositories
  /home/alexeagle/.cache/bazel/_bazel_alexeagle/1112fa9a04c6878cb3f2bf123baf106a/external/aspect_rules_js/js/npm_import.bzl:150:16: in npm_import
Repository rule npm_import defined at:
  /home/alexeagle/.cache/bazel/_bazel_alexeagle/1112fa9a04c6878cb3f2bf123baf106a/external/aspect_rules_js/js/private/npm_import.bzl:493:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm__stringify-entities__4.0.2':
   Traceback (most recent call last):
        File "/home/alexeagle/.cache/bazel/_bazel_alexeagle/1112fa9a04c6878cb3f2bf123baf106a/external/aspect_rules_js/js/private/npm_import.bzl", line 274, column 27, in _impl
                pkg_json = json.decode(rctx.read(pkg_json_path))
Error in decode: at offset 2312, object has duplicate key: "typeCoverage"
ERROR: /home/alexeagle/Projects/bazel-examples/next.js/WORKSPACE.bazel:30:17: fetching npm_import rule //external:npm__stringify-entities__4.0.2: Traceback (most recent call last):
        File "/home/alexeagle/.cache/bazel/_bazel_alexeagle/1112fa9a04c6878cb3f2bf123baf106a/external/aspect_rules_js/js/private/npm_import.bzl", line 274, column 27, in _impl
                pkg_json = json.decode(rctx.read(pkg_json_path))
Error in decode: at offset 2312, object has duplicate key: "typeCoverage"

ERROR: /home/alexeagle/Projects/bazel-examples/next.js/BUILD.bazel:4:17: //:store_link__stringify-entities__4.0.2__pkg depends on @npm__stringify-entities__4.0.2//:jsp_source_directory in repository @npm__stringify-entities__4.0.2 which failed to fetch. no such package '@npm__stringify-entities__4.0.2//': at offset 2312, object has duplicate key: "typeCoverage"
ERROR: Analysis of target '//lib:lib' failed; build aborted: 
INFO: Elapsed time: 0.347s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (7 packages loaded, 21 targets configured)
```

**Comment by gregmagolan** [comment]
Hah. Someone published a package.json with duplicate keys:

https://unpkg.com/stringify-entities@4.0.2/package.json

  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true
  },
  "typeCoverage": {
    "atLeast": 100,
    "detail": true,
    "strict": true,
    "ignoreCatch": true
  }

**Comment by gregmagolan** [comment]
We can patch the offending package.json files on the way in (there are of them):

```
translate_pnpm_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    patches = {
        # these npm packages have package.json files with duplicate 'typeCoverage' keys which
        # Bazel's json.decode fails on:
        # https://unpkg.com/stringify-entities@4.0.2/package.json
        # https://unpkg.com/decode-named-character-reference@1.0.1/package.json
        "stringify-entities@4.0.2": ["//:patches/stringify-entities@4.0.2.patch"],
        "decode-named-character-reference@1.0.1": ["//:patches/decode-named-character-reference@1.0.1.patch"],
    },
)
```

But this fix is needed so we apply the patches before reading the package.json file: https://github.com/aspect-build/rules_js/pull/149

**Comment by gregmagolan** [comment]
Left issues upstream,

https://github.com/wooorm/stringify-entities/issues/11
https://github.com/wooorm/decode-named-character-reference/issues/2
