### ISSUE TITLE
[Bug]: lock translation cache not busted causing crash

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_js#1540]
### What happened?

One example:
```
> bazel run //:gazelle
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_.../external/aspect_rules_js~override/npm/extensions.bzl", line 104, column 66, in _extension_impl
		importers, packages = translate_to_transitive_closure(lock_importers, lock_packages, attr.prod, attr.dev, attr.no_optional)
	File "/private/var/tmp/_bazel_.../external/aspect_rules_js~override/npm/private/transitive_closure.bzl", line 185, column 71, in translate_to_transitive_closure
		package_info["transitive_closure"] = gather_transitive_closure(
	File "/private/var/tmp/_bazel_.../external/aspect_rules_js~override/npm/private/transitive_closure.bzl", line 54, column 40, in gather_transitive_closure
		package_info = packages[package_key]
Error: key "@smithy/node-http-handler/2.5.0" not found in dictionary
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Uncertain
```

**Comment by jbedard** [comment]
Probably doesn't exist anymore
