### ISSUE TITLE
Example of building a Vue app

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#189]
Run `npm init vue@latest` following https://vuejs.org/guide/quick-start.html#local and then show how to run the existing build with Bazel using rules_js.

**Comment by alexeagle** [comment]
I started this here https://github.com/aspect-build/bazel-examples/tree/vue/vue
However the vite build fails at this location:
https://github.com/vitejs/vite/blob/51e9195fe94657e7ab14a22a0e7de338ad0724fd/packages/vite/src/node/config.ts#L847

stack trace:
```
▲ [WARNING] Cannot find base config file "@vue/tsconfig/tsconfig.web.json"

    ../../../tsconfig.json:2:13:
      2 │   "extends": "@vue/tsconfig/tsconfig.web.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/sandbox/linux-sandbox/323/execroot/__main__/bazel-out/k8-fastbuild/bin/vite.config.ts
error during build:
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .ts] (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:61952:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at loadConfigFromBundledFile (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:61957:17)
    at loadConfigFromFile (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:61876:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolveConfig (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:61401:28)
    at async doBuild (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:41539:20)
```

Because they check if `fs.realpathSync(fileName) === fileName` and this is false under Bazel's execution root, since it symlinks files.

**Comment by alexeagle** [comment]
Ah it looks like https://github.com/vitejs/vite/commit/a3fa1a38e4597da8c967215b0301122e8c948d7b already fixed this in vite.

**Comment by alexeagle** [comment]
Patched that commit in, but the repro branch still fails:

```
 [WARNING] Cannot find base config file "@vue/tsconfig/tsconfig.web.json"

    ../../../tsconfig.json:2:13:
      2 │   "extends": "@vue/tsconfig/tsconfig.web.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../../../execroot/__main__/bazel-out/k8-fastbuild/bin/index.html".
error during build:
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../../../execroot/__main__/bazel-out/k8-fastbuild/bin/index.html".
    at error (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:198:30)
    at FileEmitter.emitFile (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:15719:24)
    at Object.generateBundle (/shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/vite@2.9.10_@vue+tsconfig@0.1.3/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:36943:22)
```

note, this is still the error after adding a synthetic peerDep from `vite` -> `@vue/tsconfig`.

**Comment by alexeagle** [comment]
okay now that branch works:

```
$ npm run build

> vue-project@0.0.0 build
> run-p type-check build-only


> vue-project@0.0.0 type-check
> bazel test :type-check


> vue-project@0.0.0 build-only
> bazel build :dist

DEBUG: Rule 'aspect_rules_js' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "0ad478ffc9074c670618cf056647372ad6874c933859c7c8f7ea6591ef75f10c"
DEBUG: Repository aspect_rules_js instantiated at:
  /home/alexeagle/Projects/bazel-examples/vue/WORKSPACE.bazel:3:13: in <toplevel>
Repository rule http_archive defined at:
  /shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //:type-check (114 packages loaded, 962 targets configured).
INFO: Found 1 test target...

Target //:type-check up-to-date:
  bazel-bin/type-check.sh
INFO: Elapsed time: 1.850s, Critical Path: 1.62s
INFO: 358 processes: 200 internal, 2 linux-sandbox, 156 local.
//:type-check                                                            PASSED in 1.5s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 358 total actions
DEBUG: Rule 'aspect_rules_js' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "0ad478ffc9074c670618cf056647372ad6874c933859c7c8f7ea6591ef75f10c"
DEBUG: Repository aspect_rules_js instantiated at:
  /home/alexeagle/Projects/bazel-examples/vue/WORKSPACE.bazel:3:13: in <toplevel>
Repository rule http_archive defined at:
  /shared/cache/bazel/user_base/3d448bdfa11089ab2c0ca11116619b6a/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //:dist (0 packages loaded, 195 targets configured).
INFO: Found 1 target...
Target //:dist up-to-date:
  bazel-bin/dist
INFO: Elapsed time: 2.897s, Critical Path: 1.05s
INFO: 49 processes: 14 internal, 1 linux-sandbox, 34 local.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 49 total actions
alexeagle@system76-pc:~/Projects/bazel-examples/vue$ ls -R bazel-bin/dist
bazel-bin/dist:
assets  index.html

bazel-bin/dist/assets:
AboutView.56b95204.js  AboutView.ab071ea6.css  index.5966a6c8.css  index.6e1d95c3.js  logo.da9b9095.svg
```

Now it needs the remaining package.json scripts to run under bazel, in particular something to run the app in a browser and get a decent devmode.

**Comment by alexeagle** [comment]
Landed in https://github.com/aspect-build/bazel-examples/pull/11
