### ISSUE TITLE
Problem with resolving dependencies under webpack

### ISSUE THREAD

**Issue by alex-torok** [aspect-build/rules_js#220]
I'm hitting an issue with webpack resolving dependencies. I'm struggling to get a working reproduction going in the `rules_js` repo and am hoping that posting my findings so far will be enough to help diagnose the issue and see if it is related to rules_js.

Apologies if this is long-winded, but I wanted to provide as much context as possible.

The project that I'm bringing rules_js into is currently based on rules_nodejs and uses some of our own custom macros around the autogenerated `webpack_cli` (from the `bin` field of its `package.json`) to kick off a webpack build. I'm attempting to make the migration to rules_js easier for teams at my company by setting up dependency targets that choose rules_js or rules_nodejs npm targets based on a build configuration, and the different autogenerated `webpack_cli` macros based on a flag. With this, I apply a config transition on the `webpack_cli` target outputs to get my proxy targets to choose rules_js or rules_nodejs npm targets.

I'm not sure if relevant, but our repo is configured to run bazel actions in a tmpfs with `build --sandbox_base=/dev/shm` in the `.bazelrc`, which is why many of the paths in the below logs have that prefix.

I have the webpack action running with rules_js, but webpack is showing errors with resolving transitive npm dependencies.

<details>
  <summary>Click to see the full webpack error, but I'll summarize below</summary>
  
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/styles' in '/dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/esm/styles'
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/webpack@4.40.2_webpack-cli@3.3.8/node_modules/webpack/lib/Compilation.js:925:10
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/webpack@4.40.2_webpack-cli@3.3.8/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/webpack@4.40.2_webpack-cli@3.3.8/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/webpack@4.40.2_webpack-cli@3.3.8/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/neo-async@2.6.2/node_modules/neo-async/async.js:6877:13
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/webpack@4.40.2_webpack-cli@3.3.8/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:285:5
resolve '@material-ui/styles' in '/dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/esm/styles'
  Parsed request is a module
  using description file: /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/package.json (relative path: ./esm/styles)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/esm/styles/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/esm/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/node_modules doesn't exist or is not a directory
      /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/node_modules doesn't exist or is not a directory
      /dev/shm/node_modules doesn't exist or is not a directory
      /dev/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/styles doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/styles.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/styles.tsx doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/styles.js doesn't exist
        as directory
          /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/styles doesn't exist
```

</details>

Unfortunately, webpack isn't giving me a clear import stack trace to help get a reproduction working outside of our repo.

It appears like webpack is walking up from where it is in `@material-ui/core/esm/styles` to try to find `@material-ui/styles`:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/styles' in '/dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2219/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core/esm/styles'

...

/dev/shm/.../bin/node_modules/@material-ui/core/esm/styles/node_modules doesn't exist or is not a directory
/dev/shm/.../bin/node_modules/@material-ui/core/esm/node_modules doesn't exist or is not a directory
/dev/shm/.../bin/node_modules/@material-ui/core/node_modules doesn't exist or is not a directory
/dev/shm/.../bin/node_modules/@material-ui/node_modules doesn't exist or is not a directory
/dev/shm/.../bin/node_modules/node_modules doesn't exist or is not a directory
```

With pnpm linking, I would have expected it to find the realpath of the symlink for `bin/node_modules/@material-ui/core` in the sandbox, then go up to that package's node_modules directory.

It appears that the symlink target for the directory `bin/node_modules/@material-ui/core` is outside of the sandbox:

```
$ file /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core 

/dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core: 
symbolic link to 
/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core
```

I added the following debugging information to the symlink guards:
```diff
diff --git a/js/private/node-patches/fs.js b/js/private/node-patches/fs.js
index 43b628f..73cfb16 100755
--- a/js/private/node-patches/fs.js
+++ b/js/private/node-patches/fs.js
@@ -586,8 +586,15 @@ const escapeFunction = (_roots) => {
             }
         }
         if (escapedRoot) {
+            console.error(`-- SYMLINK ESCAPES --`);
+            console.error(`link:        ${linkPath}`);
+            console.error(`target:      ${linkTarget}`);
+            console.error(`escapedRoot: ${escapedRoot}`);
             return escapedRoot;
         }
+        console.error(`-- SYMLINK DOES NOT ESCAPE --`);
+        console.error(`link:   ${linkPath}`);
+        console.error(`target: ${linkTarget}`);
         return false;
     }
     return _isEscape;
```

This shows the following in my build output:
```
-- SYMLINK ESCAPES --
link:        /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/@material-ui/core
target:      /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt-ST-1db56f8cc3dd/bin/node_modules/.aspect_rules_js/@material-ui+core@4.11.0_18463140a8284ef5cda927c80b535833/node_modules/@material-ui/core
escapedRoot: /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2218/execroot/__main__
```

The parent dir of the `core` directory within the sandbox does not contain `styles`:
```
$ ls /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2219/execroot/__main__/bazel-out/k8-opt-ST
-1db56f8cc3dd/bin/node_modules/@material-ui/
core  icons  lab  types
```

If we escape the sandbox in to the realpath parent directory, we can see it there:
```
$ ls /dev/shm/bazel-sandbox.c232cb948e685633b81332a1d7238c336adde8c94b02204f66763727dc68ee39/linux-sandbox/2219/execroot/__main__/bazel-out/k8-opt-ST
-1db56f8cc3dd/bin/node_modules/@material-ui/core/..
core  styles  system  types  utils
```

I don't really understand how the symlink guards are intended to work. My best guess at this point is that our webpack build is configured in a way that it sees the `bin/node_modules/@material-ui/core` directory as not being a symlink out of the sandbox, which is causing it to not follow the links to the pnpm store for `@material-ui/core`.

I'm going to continue working on a reproduction, but I wanted to post this to see if someone more familiar with rules_js's pnpm store layout would see a glaring issue. 

🙏 Thanks for getting this far. I'll post any updates if I learn more or can get a reproduction working.

**Comment by gregmagolan** [comment]
Thanks for the detailed description @alex-torok. I'll TAL later today.

**Comment by alex-torok** [comment]
I've been trying to peel back the oddities in our repo. So far I've removed the odd transition logic (its just straight rules_js now), and the `--sandbox_base` flag from our bazelrc.

Looking at the output of `tree` for the node_modules directory, I can see the `.aspect_rules_js` store directory with all of the packages, but the actual contents link to outside of the sandbox instead of to the store directory. Following the pnpm page, I would expect the tree to link into the `.aspect_rules_js` store, but the symlinks under `node_modules` don't point to the `.aspect_rules_js` dir - https://pnpm.io/symlinked-node-modules-structure

```console
$ tree -L 2 -a /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/sandbox/linux-sandbox/6331/execroot/__main__/bazel-out/k8-opt/bin/node_modules

/home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/sandbox/linux-sandbox/6331/execroot/__main__/bazel-out/k8-opt/bin/node_modules
├── .aspect_rules_js
│   ├── @ampproject+remapping@2.2.0
│   ├── @babel+code-frame@7.12.11
│   ├── @babel+code-frame@7.16.7
│   ├── @babel+compat-data@7.17.10
│   ├── @babel+core@7.18.2
...
│   ├── yauzl@2.10.0
│   └── yocto-queue@0.1.0
├── @babel
│   ├── preset-env -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/@babel/preset-env
│   └── runtime -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/@babel/runtime
├── @danmarshall
│   └── deckgl-typings -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/@danmarshall/deckgl-typings
...
├── webpack-merge -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/webpack-merge
├── wellknown -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/wellknown
├── whatwg-fetch -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/whatwg-fetch
└── worker-loader -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/f8d954fb8d563619a1a7548575ac13e0/execroot/__main__/bazel-out/k8-opt/bin/node_modules/worker-loader
```

I was able to reproduce seeing this structure in rules_js, but haven't gotten a true failing test that shows my issue with not resolving transitive deps (I'll take a look again on Monday if need be).

1. Apply the following patch:
```diff
diff --git a/examples/js_binary/BUILD.bazel b/examples/js_binary/BUILD.bazel
index 482f010..4dd09a0 100644
--- a/examples/js_binary/BUILD.bazel
+++ b/examples/js_binary/BUILD.bazel
@@ -66,6 +66,7 @@ js_test(
     name = "test_test",
     data = ["//:node_modules/@types/node"],
     entry_point = "test.js",
+    log_level = "debug",
 )

 ###############################
diff --git a/examples/js_binary/test.js b/examples/js_binary/test.js
index c593c7c..f0dd1e8 100644
--- a/examples/js_binary/test.js
+++ b/examples/js_binary/test.js
@@ -1 +1,2 @@
 console.log(require.resolve('@types/node/package.json'))
+process.exit(1)
```
2. `bazel test --sandbox_debug //examples/js_binary:test_test`
3. Look in the test failure log for `INFO: aspect_rules_js[js_test]: PWD <some_dir>`
4. Look at the structure of the node_modules directory:
```
$ tree -a  <some_dir>
<some_dir>
├── .aspect_rules_js
│   └── @types+node@registry.npmjs.org+@types+node+16.11.36
│       └── node_modules
│           └── @types
│               └── node
│                   ├── LICENSE -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/LICENSE
│                   ├── README.md -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/README.md
│                   ├── assert
│                   │   └── strict.d.ts -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/assert/strict.d.ts
...
│                   ├── wasi.d.ts -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/wasi.d.ts
│                   ├── worker_threads.d.ts -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/worker_threads.d.ts
│                   └── zlib.d.ts -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@types+node@registry.npmjs.org+@types+node+16.11.36/node_modules/@types/node/zlib.d.ts
└── @types
    └── node -> /home/alex.torok/.cache/bazel/_bazel_alex.torok/a35b6b5cd0642228cee40197cc66bc5c/execroot/aspect_rules_js/bazel-out/k8-fastbuild/bin/node_modules/@types/node

12 directories, 54 files
```

**Comment by gregmagolan** [comment]
The sandbox ends up being a farm of symlinks to their counterparts outside of the sandbox. This makes resolving symlinks within the sandbox a bit tricky since you have to check if the file outside of the sandbox is a symlink if you are resolving with realpath then the result must be re-mapped to the corresponding path within the sandbox. The symlinks guards handle this complication but it might be that there is a bug or webpack symlink resolves someone works around the guards.

I think I need a minimal repro of the webpack issue to debug where things are going wrong.

**Comment by gregmagolan** [comment]
Fix landed finally. Thanks for your help on this one. I made the webpack_cli example a separate commit and attributed it to you https://github.com/aspect-build/rules_js/commit/d4ac0ccbd4a87d1d44a4f0253b54e3c0ab4f4bf0
