### ISSUE TITLE
macro example has a hidden require failure

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#345]
The output is hidden by default since the tests themselves pass despite this require failure, but it shows up with `--test_output=all`:

```
~/figma/rules_js $ bazel test --test_output=all //examples/macro:test
INFO: Analyzed target //examples/macro:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //examples/macro:test up-to-date:
  bazel-bin/examples/macro/test.sh
INFO: Elapsed time: 0.216s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
PASSED: //examples/macro:test (see /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/testlogs/examples/macro/test/test.log)
INFO: From Testing //examples/macro:test
==================== Test output for //examples/macro:test:
Failed to load reporter: "mocha-junit-reporter" or "/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/mocha-junit-reporter": Error: Cannot find module 'mocha-junit-reporter'
Require stack:
- /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha-multi-reporters@1.5.1_mocha@10.0.0/node_modules/mocha-multi-reporters/lib/MultiReporters.js
- /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha-multi-reporters@1.5.1_mocha@10.0.0/node_modules/mocha-multi-reporters/index.js
- /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/lib/cli/run-helpers.js
- /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/lib/cli/options.js
- /private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/bin/mocha.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at MultiReporters.processReporterEnabled (/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha-multi-reporters@1.5.1_mocha@10.0.0/node_modules/mocha-multi-reporters/lib/MultiReporters.js:75:36)
    at Array.map (<anonymous>)
    at new MultiReporters (/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha-multi-reporters@1.5.1_mocha@10.0.0/node_modules/mocha-multi-reporters/lib/MultiReporters.js:54:44)
    at Mocha.run (/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/lib/mocha.js:981:18)
    at singleRun (/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/lib/cli/run-helpers.js:126:16)
    at async Object.exports.handler (/private/var/tmp/_bazel_johnfirebaugh/3cc5be9735d30b6128426fd19d172550/sandbox/darwin-sandbox/6/execroot/aspect_rules_js/bazel-out/darwin-fastbuild/bin/examples/macro/test.sh.runfiles/aspect_rules_js/node_modules/.aspect_rules_js/mocha@10.0.0_th2rfume6p4m5jxelm27wrhnly/node_modules/mocha/lib/cli/run.js:370:5)
Reporter not found! mocha-junit-reporter


  mocha
    ✔ integrates with Bazel


  1 passing (2ms)

================================================================================
//examples/macro:test                                           (cached) PASSED in 0.6s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action
```

This seems specific to the directory / symlink structure set up by rules_js. I thought it might be that mocha-multi-reporters is incompatible with pnpm, but that appears not to be the case because `cd examples/macro && pnpm install && MOCHA_FILE=test.xml ./node_modules/.bin/mocha --reporter mocha-multi-reporters --reporter-options configFile=./mocha_reporters.json test.js` succeeds and generates `test.xml`.

**Comment by alexeagle** [comment]
Maybe mocha-junit-reporter needs to be hoisted here too https://github.com/aspect-build/rules_js/blob/main/package.json#L12

**Comment by jfirebaugh** [comment]
Fixed by https://github.com/aspect-build/rules_js/pull/355.
