### ISSUE TITLE
/npm/pnpm-lock.yaml (No such file or directory)

### ISSUE THREAD

**Issue by uhthomas** [aspect-build/rules_js#396]
Given

##### WORKSPACE

```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "aspect_rules_js",
    sha256 = "538049993bec3ee1ae9b1c3cd669156bca04eb67027b222883e47b0a2aed2e67",
    strip_prefix = "rules_js-1.0.0",
    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.0.0.tar.gz",
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")

rules_js_dependencies()

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = DEFAULT_NODE_VERSION,
)

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    package_json = "//:package.json",
    verify_node_modules_ignored = "//:.bazelignore",
    yarn_lock = "//:yarn.lock",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()
```

Error:

```
❯ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Repository npm instantiated at:
  /Users/thomas/code/sourcegraph/WORKSPACE:23:19: in <toplevel>
  /private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/npm_import.bzl:55:28: in npm_translate_lock
Repository rule npm_translate_lock_rule defined at:
  /private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/npm_import.bzl:32:42: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 597, column 37, in _impl
                lockfile = _process_lockfile(rctx, "pnpm-lock.yaml")
        File "/private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 199, column 47, in _process_lockfile
                lockfile = utils.parse_pnpm_lock(rctx.read(rctx.path(pnpm_lock)))
Error in read: java.io.FileNotFoundException: /private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/npm/pnpm-lock.yaml (No such file or directory)
ERROR: /Users/thomas/code/sourcegraph/WORKSPACE:23:19: fetching npm_translate_lock_rule rule //external:npm: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 597, column 37, in _impl
                lockfile = _process_lockfile(rctx, "pnpm-lock.yaml")
        File "/private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 199, column 47, in _process_lockfile
                lockfile = utils.parse_pnpm_lock(rctx.read(rctx.path(pnpm_lock)))
Error in read: java.io.FileNotFoundException: /private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/npm/pnpm-lock.yaml (No such file or directory)
ERROR: no such package '@npm//': java.io.FileNotFoundException: /private/var/tmp/_bazel_thomas/371526a2a92600fa64bb909f1dd7a076/external/npm/pnpm-lock.yaml (No such file or directory)
INFO: Elapsed time: 4.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

package.json: https://github.com/sourcegraph/sourcegraph/blob/v3.41.1/package.json
yarn.lock: https://github.com/sourcegraph/sourcegraph/blob/v3.41.1/yarn.lock

**Comment by uhthomas** [comment]
This also happens with [@HEAD](68f8156d1774911981aeea569d069fbe55acc443).

**Comment by uhthomas** [comment]
I suspect this is probably an uncaught error from `pnpm`...

```
❯ npx pnpm install --lockfile-only
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sourcegraph%2Feslint-plugin-wildcard: Not Found - 404

@sourcegraph/eslint-plugin-wildcard is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 27, reused 18, downloaded 4, added 0
```

**Comment by uhthomas** [comment]
Okay, so I managed to get pnpm working. I came across this useful snippet when reading the import documentation:

>Note that if you have workspaces you wish to import dependencies for, they will need to be declared in a [pnpm-workspace.yaml](https://pnpm.io/pnpm-workspace_yaml) file beforehand.
>
>https://pnpm.io/cli/import
>

I created a `pnpm-workspace.yaml` as per the documentation.

```yaml
packages:
- client/*
```

Then it worked!

```
❯ npx pnpm install --lockfile-only
Scope: all 22 workspace projects
```

---

I don't see any support for the `pnpm-workspace.yaml` within `rules_js`. Have you encountered this before? How can we make sure `pnpm` errors are correctly handled? Should this be documented? Should support for importing workspaces be added?

Many thanks

**Comment by uhthomas** [comment]
Just to confirm -- the generated `pnpm-lock.yaml` given the fix seems to work okay.

```
❯ bazel build //...
INFO: Analyzed 0 targets (2 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 4.449s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

**Comment by alexeagle** [comment]
Yes, we support pnpm-workspace.yaml implicitly, because you're expected to run the pnpm resolver ahead-of-time to bring a pnpm-lock.yaml file to rules_js. By that time, all the workspace bits are reflected in the lockfile so we don't care about the pnpm-workspace.yaml.

However when importing a yarn.lock or package-lock.json, it looks like we should add a check for that content so we can warn.

**Comment by alexeagle** [comment]
First step there was to fix the embarrassing missing error handling.

Now, why does `pnpm import` fail on a yarn.lock with workspaces? Seems like an upstream bug to me. It should check that there's a workspaces key before blindly trying to fetch all packages from npm...

```
npx pnpm@latest import
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sourcegraph%2Feslint-plugin-wildcard: Not Found - 404

@sourcegraph/eslint-plugin-wildcard is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer 386d[hidden]
Progress: resolved 18, reused 18, downloaded 0, added 0
```

Since Bazel behavior is now the same as outside of Bazel I'm tempted to close this as WAI...

**Comment by alexeagle** [comment]
https://pnpm.io/cli/import:
> Note that if you have workspaces you wish to import dependencies for, they will need to be declared in a [pnpm-workspace.yaml](https://pnpm.io/pnpm-workspace_yaml) file beforehand.

If we want better error handling, let's file upstream: https://github.com/pnpm/pnpm/issues/5240
