### ISSUE TITLE
[Bug]: postinstall breaks on some npm packages 

### ISSUE THREAD

**Issue by Tomsons** [aspect-build/rules_js#715]
### What happened?

Some libraries use binaries that it assumes being present on the host machine such as `npm` for example. Below you will find a compilation of libraries that are supposed to work with a traditional `npm | yarn install`:
-  [@cubejs-backend/cubestore@0.30.75](https://www.npmjs.com/package/@cubejs-backend/cubestore) that uses `npm config` to somehow use a npm config proxy setting
```
Running lifecycle hooks on npm package @cubejs-backend/cubestore@0.30.75_moment@2.29.4 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh @cubejs-backend/cubestore ... (remaining 2 arguments skipped)

Cube.js Cube Store Installer ---------------------------------------

Command failed: npm config get https-proxy
/bin/sh: npm: command not found


Need some help? -------------------------------------

  Ask this question in Cube.js Slack: https://slack.cube.dev
  Post an issue: https://github.com/cube-js/cube.js/issues


> @cubejs-backend/cubestore@0.30.75 postinstall /private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@cubejs-backend+cubestore@0.30.75_moment@2.29.4/node_modules/@cubejs-backend/cubestore
> node bin/post-install

===============================================================
Failure while running lifecycle hook for package '@cubejs-backend/cubestore@0.30.75':

  Script:  'postinstall'
  Command: `node bin/post-install`

Stack trace:

Exit status 1
    at EventEmitter.<anonymous> (/private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:73836)
    at EventEmitter.emit (node:events:527:28)
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:80298)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
===============================================================

```
- `java` node binding: used by the [CubeJS databricks driver](https://www.npmjs.com/package/@cubejs-backend/databricks-jdbc-driver) which throws the following error
```
/private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/node-gyp-bin/node-gyp: line 5: 1010: command not found

> java@0.12.2 install /private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/java@0.12.2/node_modules/java
> node-gyp rebuild

===============================================================
Failure while running lifecycle hook for package 'java@0.12.2':

  Script:  'install'
  Command: `node-gyp rebuild`

Stack trace:

spawn ENOENT
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_tom/73cb73ab0898b3083f041554c626fd30/execroot/wm/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:80170)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
===============================================================
INFO: Elapsed time: 4.260s, Critical Path: 0.48s
INFO: 1376 processes: 1101 internal, 4 darwin-sandbox, 271 local.
FAILED: Build did NOT complete successfully
``` 

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 5.1.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 1.10.0

Language(s) and/or frameworks involved: - 

### How to reproduce

```shell
Add following npm packages in your package.json file:

- "@cubejs-backend/databricks-jdbc-driver": "0.30.75"
- "@cubejs-backend/cubestore-driver": "0.30.75"

Use them in a rules_js | rules_ts specific target
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by joac** [comment]
Seems related/same bug as https://github.com/aspect-build/rules_js/issues/217

**Comment by gregmagolan** [comment]
Lifecycle hooks for some npm packages are just problematic as outside of Bazel you have your whole node_modules tree layed out while within Bazel dependencies are strict so if a package doesn't declare a dependency on a tool it needs to a postinstall then it may fail.

There are a few cases reported here so I'll go through them one-by-one.

1) The `npm: command not found` should be fixed in the latest rules_js release. The lifecycle js_binary now has the Bazel fetched `npm` on the PATH. Outside of Bazel, the hooks depend on `npm` being installed globally on your local machine but within Bazel we want to depend on the node/npm version from the toolchain in your WORKSPACE instead.

2) `prepare` hooks are particularly problematic. This lifecycle hook tends to be present in npm packages that are fetched from source directly from GitHub and they are "built" in the `prepare` hook by the consumer instead of being built and published to an npm registry. rules_js doesn't run these hooks by default since they generally depend on the `devDependencies` of a package and rules_js doesn't currently fetch these and lay them out for the package.

> Fetching `devDependencies` is an improvement we can make but the trade-off there is that the `devDependencies` would leak as transitive deps to rules that depend on the npm package so some work would need to be done to prevent that from happening which makes the change non-trivial.

I tackled the "prepare" hook at a client migration in the last few weeks and now have an example of how to handle it here:

To turn on the hook, use the `lifecycle_hooks` attribute of `npm_translate_lock`:

https://github.com/aspect-build/rules_js/blob/132f52dea2b3f1bea1211c52872ffd32ee7261eb/WORKSPACE#L95

Any `devDependencies` in the package that are required need to be hoisted to `dependencies` using `pnpm.packageExtensions` in your `package.json`:

https://github.com/aspect-build/rules_js/blob/132f52dea2b3f1bea1211c52872ffd32ee7261eb/package.json#L29

3) `node-gyp` deps are tricky and I don't believe understand all the different ways this can fail.

I spend a bit of time on this in the last few weeks and have one example up in rules_js of an npm package (`segfault-handler`) that has a node-gyp build step: https://github.com/aspect-build/rules_js/blob/132f52dea2b3f1bea1211c52872ffd32ee7261eb/npm/private/test/BUILD.bazel#L62

In this case, I had to add `node-gyp` to the `dependencies` of the package so that the `node_modules/.bin/node-gyp` is found for the build step: https://github.com/aspect-build/rules_js/blob/132f52dea2b3f1bea1211c52872ffd32ee7261eb/package.json#L23

There are probably other cases and maybe a more robust solution in the rules_js lifecycle hook code that could be made to make `node-gyp` build steps work out of the box for many if not all packages. Looks like @joac has done some investigation into this in https://github.com/aspect-build/rules_js/issues/217. I plan to spend some time on it next week as it will be a quiet week and I will have time for a round of OSS bug squashes and features.
