### ISSUE TITLE
[Bug]: bzlmod seems broken with workspaces

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#729]
### What happened?

Here's a repro:

https://github.com/aspect-build/rules_ts/compare/fetch_subpkg

```shell
alexeagle@system76-pc:~/Projects/rules_ts$ cd e2e/bzlmod
alexeagle@system76-pc:~/Projects/rules_ts/e2e/bzlmod$ bazel fetch ...
ERROR: Evaluation of query "deps(...)" failed: preloading transitive closure failed: no such target '//:.aspect_rules_js/node_modules/long@5.2.1': target '.aspect_rules_js/node_modules/long@5.2.1' not declared in package '' defined by /home/alexeagle/Projects/rules_ts/e2e/bzlmod/BUILD (Tip: use `query "//:*"` to see all the targets in that package)
```

### Version

rules_js 1.8.0 and 1.11.1 at least

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment]
@gregmagolan says this is because the virtual store gets created by a ` npm_link_all_packages` in the `/BUILD.bazel` but I didn't have one there. I wonder if we can detect that and give a better error.

**Comment by gregmagolan** [comment]
@kormide Is this one resolved with all the work you landed?

**Comment by kormide** [comment]
@gregmagolan I reproduced @alexeagle 's changes and got this error instead.

```
ERROR: Traceback (most recent call last):
        File "/Users/derek/Code/rules_ts/e2e/bzlmod/pkg/BUILD.bazel", line 3, column 22, in <toplevel>
                npm_link_all_packages(name = "node_modules")
        File "/private/var/tmp/_bazel_derek/d2176dd9c2783092eb773cbca42d101b/external/aspect_rules_js~1.17.0~npm~npm/defs.bzl", line 123, column 13, in npm_link_all_packages
                fail(msg)
Error in fail: The npm_link_all_packages() macro loaded from @aspect_rules_js~1.17.0~npm~npm//:defs.bzl and called in bazel package 'pkg' may only be called in the bazel package(s) corresponding to the root package '' and packages ['']
```

Looks better to me, but this part is a bit confusing:
```
corresponding to the root package '' and packages ['']
```

**Comment by gregmagolan** [comment]
Thanks for checking. That error could improve a bit. Its a small change so I'll cue it up.
