### ISSUE TITLE
Npm alias protocol does not resolve

### ISSUE THREAD

**Issue by stoiky** [aspect-build/rules_js#86]
As per https://yarnpkg.com/features/protocols a package name may have an alias to another package in the form of:
```
"react-intl-cdo": "npm:react-intl@2.8.0", 
```

This in `pnpm-lock.yaml` transforms to `react-intl-cdo: /react-intl/2.8.0_prop-types@15.7.2+react@17.0.1` and will fail inside `js/private/translate_pnpm_lock.js` with the error below because the `pnpmName` will be `react-intl-cdo//react-intl/2.8.0_prop-types@15.7.2+react@17.0.1`

```
(node:54092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dependencies' of undefined
    at gatherTransitiveClosure 
(/Users/mstoichi/code/github.com/rules_js/js/private/translate_pnpm_lock.js:52:34)
    at main (/Users/mstoichi/code/github.com/rules_js/js/private/translate_pnpm_lock.js:188:9)
```

**Comment by gregmagolan** [comment]
I'll pick this one up next week

**Comment by kzadorozhny** [comment]
`v0.11.0` fails with error:
```
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_zadorozh/a141ef13fb1568f0df4f5afbc3b9310b/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 319, column 33, in _impl
		lockfile = _process_lockfile(rctx)
	File "/private/var/tmp/_bazel_zadorozh/a141ef13fb1568f0df4f5afbc3b9310b/external/aspect_rules_js/npm/private/npm_translate_lock.bzl", line 145, column 43, in _process_lockfile
		return translate_to_transitive_closure(lockfile, rctx.attr.prod, rctx.attr.dev, rctx.attr.no_optional)
	File "/private/var/tmp/_bazel_zadorozh/a141ef13fb1568f0df4f5afbc3b9310b/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 114, column 34, in translate_to_transitive_closure
		gather_transitive_closure(
	File "/private/var/tmp/_bazel_zadorozh/a141ef13fb1568f0df4f5afbc3b9310b/external/aspect_rules_js/npm/private/transitive_closure.bzl", line 34, column 36, in gather_transitive_closure
		package_info = packages[utils.pnpm_name(name, version)]
Error: key "react-intl-cdo//react-intl/2.8.0_prop-types@15.8.1+react@17.0.1" not found in dictionary
```

**Comment by gregmagolan** [comment]
I started to look at just now and the code needs a bit of refactoring to support these link aliases in npm_import and npm_translate_lock. I'll pick it up again tomorrow.
