### ISSUE TITLE
[Bug]: portal in sub dir Cannot find module when js run binary

### ISSUE THREAD

**Issue by hunshcn** [aspect-build/rules_js#958]
### What happened?

a example here https://github.com/hunshcn/bazel_rules_js_vue2_service_replay

to replay it 

```
bazel build //portal:build
```

error message:
```
-  Building for production...
 ERROR  Error: Cannot find module 'vue-template-compiler'
Require stack:
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/compiler.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/plugin-webpack4.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/plugin.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/config/base.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/Service.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'vue-template-compiler'
Require stack:
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/compiler.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/plugin-webpack4.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/plugin.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/config/base.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/Service.js
- /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at loadFromContext (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/compiler.js:30:26)
    at loadTemplateCompiler (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/compiler.js:37:12)
    at exports.resolveCompiler (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/compiler.js:25:23)
    at VueLoaderPlugin.apply (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/vue-loader@15.10.1_m6jvttnwtqqy6l4pi5vsxiehsy/node_modules/vue-loader/lib/plugin-webpack4.js:91:22)
    at webpack (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/webpack@4.46.0/node_modules/webpack/lib/webpack.js:51:13)
    at /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5
    at new Promise (<anonymous>)
    at build (/private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/commands/build/index.js:191:10)
    at async /private/var/tmp/_bazel_user1/cd9a412314ff679262e78525a6284f08/sandbox/darwin-sandbox/2163/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/portal/node_modules/.aspect_rules_js/@vue+cli-service@4.3.1_ev5jzj74xu2fombjvobqpq452a/node_modules/@vue/cli-service/lib/commands/build/index.js:88:7

Target //portal:build failed to build
```

has no error if mv project to the root of project. only error when portal folder is not the root of workspace.

here is a example change portal to root (https://github.com/hunshcn/bazel_rules_js_vue2_service_replay/tree/okay), it works

### Version

bazel 5.4.0
rules_js 1.23.1

**Comment by hunshcn** [comment]
similar to https://github.com/aspect-build/rules_js/issues/599 ?
@gregmagolan

**Comment by hunshcn** [comment]
sorry, thought long time debug, I find that it error because i don't set chdir to `js_run_binary`.

but maybe example this? or highlight it in docs?
