### ISSUE TITLE
[FR]: Add support for "injected" in "dependenciesMeta"

### ISSUE THREAD

**Issue by duarten** [aspect-build/rules_js#959]
### What is the current behavior?

A dependency for which a `dependenciesMeta` entry exists will fail with an error like:

```
(21:34:32) ERROR: Traceback (most recent call last):
	File "/Users/duarte.nunes/code/umani/BUILD.bazel", line 10, column 22, in <toplevel>
		npm_link_all_packages(name = "node_modules")
	File "/private/var/tmp/_bazel_duarte.nunes/f66c51e6a3394c97f40c1dcafe76e7fd/external/npm/defs.bzl", line 5548, column 27, in npm_link_all_packages
		_npm_package_store(
Error in npm_package_store: npm_package_store rule '.aspect_rules_js/node_modules/@ui+amanara@0.0.0' in package '' conflicts with existing npm_package_store rule, defined at /Users/duarte.nunes/code/umani/BUILD.bazel:10:22
```

### Describe the feature

The motivation is to be able to correctly support peer dependencies for workspace packages: https://pnpm.io/package_json#dependenciesmetainjected.

**Comment by Silic0nS0ldier** [comment]
Working upgrading from pnpm v8 to v9 and I've been coming across issues around this feature (escalated from unsupported and liable to not match pnpm behaviour, to outright broken).

-----

First, conflicting targets like the OP describes. In our case this came up _specifically_ when the injected package had a mix of injected and non-injected local dependencies. Marking all those as injected solved the issue.

```
ERROR: Traceback (most recent call last):
	File "/[repo-root]/BUILD.bazel", line 10, column 22, in <toplevel>
		npm_link_all_packages(name = "node_modules")
	File "/[bazel-output-root]/external/pnpm_deps/defs.bzl", line 15857, column 27, in npm_link_all_packages
		_npm_package_store(
Error in npm_package_store: npm_package_store rule '.aspect_rules_js/node_modules/@canva+logging@0.0.0' in package '' conflicts with existing npm_package_store rule, defined at /[repo-root]/BUILD.bazel:10:22
```

-----

Once that issue was workaround, another issue came up for a package that _actually_ has peer dependencies (one, `typescript`).

```
ERROR: no such package 'tools/dependency_tree_typescript_5.5.4': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /[repo-root]/tools/dependency_tree_typescript_5.5.4
ERROR: /[repo-root]/BUILD.bazel:10:22: no such package 'tools/dependency_tree_typescript_5.5.4': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /[repo-root]/tools/dependency_tree_typescript_5.5.4 and referenced by '//:.aspect_rules_js/node_modules/@canva+dependency-tree@0.0.0'
```

The malformed codegen for that is like as follows.

```starlark
    if is_root:
        _npm_package_store(
            name = ".aspect_rules_js/{}/@canva+dependency-tree@0.0.0".format(name),
            # Should be //tools/dependency_tree:pkg
            src = "//tools/dependency_tree_typescript_5.5.4:pkg",
            package = "@canva/dependency-tree",
            version = "0.0.0",
            deps = {
                # ...
            },
            visibility = ["//visibility:public"],
            tags = ["manual"],
        )
```

Digging into `//npm/private/pnpm.bzl` showed that `_convert_pnpm_v6_v9_version_peer_dep` is being given input it's doc block does not indicate is covered.

Given: `@canva/dependency-tree@file:tools/dependency_tree(typescript@5.5.4)`
Expected: `file:tools/dependency_tree(typescript@5.5.4)` (based on usage in `_convert_v6_packages`)

**Comment by Silic0nS0ldier** [comment]
More info. Here is how `_convert_v6_packages` and `_convert_v9_packages` differ output wise.

```json
// v8
    "file:tools/dependency_tree_typescript_5.5.4": {
        "dependencies": {
            // ...
        },
        "dev": true,
        "friendly_version": "file:tools/dependency_tree_typescript_5.5.4",
        "has_bin": false,
        "id": "file:tools/dependency_tree",
        "name": "@canva/dependency-tree",
        "optional": false,
        "optional_dependencies": {},
        "requires_build": false,
        "resolution": {
            "directory": "tools/dependency_tree",
            "type": "directory"
        },
        "version": "file:tools/dependency_tree_typescript_5.5.4"
    },
```

```json
// v9
    "@canva/dependency-tree@file:tools/dependency_tree_typescript_5.5.4": {
        "dependencies": {
            // ...
        },
        "dev": null,
        "friendly_version": "file:tools/dependency_tree",
        "has_bin": false,
        "id": null,
        "name": "@canva/dependency-tree",
        "optional": false,
        "optional_dependencies": {},
        "requires_build": null,
        "resolution": {
            "directory": "tools/dependency_tree",
            "type": "directory"
        },
        "version": "file:tools/dependency_tree_typescript_5.5.4"
    },
```

I believe there are some processing discrepancies elsewhere (e.g. importers).
